// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelAllJobs(arg1) {
  return window['go']['main']['App']['CancelAllJobs'](arg1);
}

export function Diagnose(arg1) {
  return window['go']['main']['App']['Diagnose'](arg1);
}

export function ExportFile(arg1, arg2) {
  return window['go']['main']['App']['ExportFile'](arg1, arg2);
}

export function ExportPRN(arg1) {
  return window['go']['main']['App']['ExportPRN'](arg1);
}

export function FeedLabel(arg1) {
  return window['go']['main']['App']['FeedLabel'](arg1);
}

export function ListPrinters() {
  return window['go']['main']['App']['ListPrinters']();
}

export function LoadTemplate(arg1) {
  return window['go']['main']['App']['LoadTemplate'](arg1);
}

export function OpenImage() {
  return window['go']['main']['App']['OpenImage']();
}

export function OpenPrintQueue(arg1) {
  return window['go']['main']['App']['OpenPrintQueue'](arg1);
}

export function OpenTemplate() {
  return window['go']['main']['App']['OpenTemplate']();
}

export function Print(arg1) {
  return window['go']['main']['App']['Print'](arg1);
}

export function ProofPDF(arg1) {
  return window['go']['main']['App']['ProofPDF'](arg1);
}

export function SaveTemplate(arg1, arg2) {
  return window['go']['main']['App']['SaveTemplate'](arg1, arg2);
}
