// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelAllJobs(arg1:string):Promise<number>;

export function Diagnose(arg1:string):Promise<Array<main.DiagResult>>;

export function ExportFile(arg1:main.PrintRequest,arg2:string):Promise<string>;

export function ExportPRN(arg1:main.PrintRequest):Promise<string>;

export function FeedLabel(arg1:main.PrintRequest):Promise<void>;

export function ListPrinters():Promise<main.PrinterList>;

export function LoadTemplate(arg1:string):Promise<main.TemplateFile>;

export function OpenImage():Promise<string>;

export function OpenPrintQueue(arg1:string):Promise<void>;

export function OpenTemplate():Promise<main.TemplateFile>;

export function Print(arg1:main.PrintRequest):Promise<string>;

export function ProofPDF(arg1:main.PrintRequest):Promise<void>;

export function SaveTemplate(arg1:string,arg2:string):Promise<string>;
